# SPDX-FileCopyrightText: 2024 shadPS4 Emulator Project
# SPDX-License-Identifier: GPL-2.0-or-later

name: Windows-Qt

on:
  push:
    branches: [ "ccache" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
          submodules: recursive

    - name: Setup Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: 6.7.2
        host: windows
        target: desktop
        arch: win64_msvc2019_64
        archives: qtbase qttools

    - name: Set up build environment (windows-latest)
      run: |
          iwr -useb 'https://raw.githubusercontent.com/scoopinstaller/install/master/install.ps1' -outfile 'install.ps1'
          .\install.ps1 -RunAsAdmin
          scoop install ninja sccache --global
          echo "${env:PATH}" >> ${env:GITHUB_PATH}

    - uses: actions/cache@v4
      with:
          path: ~\AppData\Local\Mozilla\sccache
          key: ccache-windows-release-${{ github.sha }}
          restore-keys: ccache-windows-release-

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -T ClangCL -DENABLE_QT_GUI=ON -DCMAKE_C_COMPILER_LAUNCHER=sccache -DCMAKE_CXX_COMPILER_LAUNCHER=sccache

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --parallel

    - name: Deploy
      run: |
        mkdir upload
        move build/Release/shadPS4.exe upload
        move build/translations upload
        windeployqt --dir upload upload/shadPS4.exe

    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: shadps4-win64-qt
        path: upload
